<a href="https://colab.research.google.com/github/muesgit/deep_learning_tutorial/blob/main/Deep_Learning_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

In [8]:
my_list = [1, 2, 3, 4, 5]
print(my_list)

[1, 2, 3, 4, 5]


In [10]:
np1 = np.random.rand(3,4)
print(np1)

[[0.40397655 0.25474458 0.31945533 0.06054548]
 [0.68483947 0.89495258 0.51399674 0.31597173]
 [0.06268964 0.04447175 0.75604887 0.80736548]]


In [11]:
np.dtype

numpy.dtype

In [12]:
np1.dtype

dtype('float64')

In [13]:
tensor2d = torch.rand(3,4)
print(tensor2d)

tensor([[0.3329, 0.4979, 0.9614, 0.4601],
        [0.3942, 0.3798, 0.7062, 0.9278],
        [0.8505, 0.5857, 0.9483, 0.4062]])


In [14]:
tensor3d = torch.zeros(2,3,4)
print(tensor3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [16]:
## Create tensor out of numpy array
mytens = torch.tensor(np1)
print(mytens)

tensor([[0.4040, 0.2547, 0.3195, 0.0605],
        [0.6848, 0.8950, 0.5140, 0.3160],
        [0.0627, 0.0445, 0.7560, 0.8074]], dtype=torch.float64)


In [17]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Reshape and View

In [20]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
# Reshape if we dont know the number of items

In [22]:
my_torch2 = torch.arange(10)

In [23]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_torch7[7]

tensor(7)

In [28]:
my_torch8 = my_torch7.reshape(5,2)

In [29]:
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [30]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [31]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [32]:
# Video 4

In [33]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [34]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [35]:
# Addition Longhand

In [36]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [37]:
# Remainder
tensor_a % tensor_b
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [39]:
# Reassignment
tensor_a += tensor_b
tensor_a

tensor([11, 14, 17, 20])

In [40]:
tensor_a.add_(tensor_b)

tensor([16, 20, 24, 28])

In [41]:
# Video 5